/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ComponentOptions {
  /**
   * The name of the component.
   */
  name: string;
  /**
   * The path to create the service.
   */
  path?: string;
  /**
   * Only supports ts.
   */
  language?: string;
  /**
   * iCodeX service source root directory.
   */
  sourceRoot?: string;
  /**
   * The type of the component.
   */
  type: string;
}
