/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OpenapiGenOptions {
  /**
   * iCodeX service source root directory.
   */
  sourceRoot?: string;
  /**
   * The OpenAPI spec file path.
   */
  inputSpec: string;
  /**
   * The output directory for generated files.
   */
  outputDir: string;
  /**
   * The generator to use.
   */
  generator: "typescript-fetch" | "typescript-deno";
}
